package ironman.presentacion;

import java.awt.Graphics;
import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * 
 * 
 * 
 */
public class prueba extends javax.swing.JFrame {
    private String carpetaImagenes = "D:\\Workspace\\UD\\modelos1\\Lab_2\\IronMan\\src\\ironman\\presentacion\\imagenes\\";
    private int numArmadura;

    private Modelo modelo;

    /**
     * Creates new form vistaPrincipal
     */
    public prueba(Modelo modelo) {
        this.modelo = modelo;
        initComponents();

        agregarEventos();
    }

    private void agregarEventos() {
        getjComboBox1().addActionListener(modelo.getVistaPedir().getControl());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCaracteristicas = new javax.swing.JTextArea();
        jpTraje = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombreTraje = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        jpImgArmadura = new javax.swing.JPanel();
        jpElemento = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jpImgElemento = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Caracteristicas");

        jtaCaracteristicas.setColumns(20);
        jtaCaracteristicas.setLineWrap(true);
        jtaCaracteristicas.setRows(5);
        jtaCaracteristicas.setTabSize(4);
        jtaCaracteristicas.setEnabled(false);
        jScrollPane1.setViewportView(jtaCaracteristicas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(229, 229, 229))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpTraje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Traje");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad");

        lblNombreTraje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombreTraje.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpImgArmaduraLayout = new javax.swing.GroupLayout(jpImgArmadura);
        jpImgArmadura.setLayout(jpImgArmaduraLayout);
        jpImgArmaduraLayout.setHorizontalGroup(
            jpImgArmaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpImgArmaduraLayout.setVerticalGroup(
            jpImgArmaduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpTrajeLayout = new javax.swing.GroupLayout(jpTraje);
        jpTraje.setLayout(jpTrajeLayout);
        jpTrajeLayout.setHorizontalGroup(
            jpTrajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTrajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTrajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpImgArmadura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpTrajeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreTraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpTrajeLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpTrajeLayout.setVerticalGroup(
            jpTrajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTrajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTrajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreTraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpTrajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpImgArmadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpElemento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Casco", "Peto", "Guantes", "Botas" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Objeto");

        javax.swing.GroupLayout jpImgElementoLayout = new javax.swing.GroupLayout(jpImgElemento);
        jpImgElemento.setLayout(jpImgElementoLayout);
        jpImgElementoLayout.setHorizontalGroup(
            jpImgElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpImgElementoLayout.setVerticalGroup(
            jpImgElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpElementoLayout = new javax.swing.GroupLayout(jpElemento);
        jpElemento.setLayout(jpElementoLayout);
        jpElementoLayout.setHorizontalGroup(
            jpElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpElementoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpImgElemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpElementoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpElementoLayout.setVerticalGroup(
            jpElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpElementoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpImgElemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpTraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpElemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpTraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void putTraje() {
        String rutaImgTraje = carpetaImagenes + obtenerNombreArmadura() + ".jpg";

        // System.out.println(rutaImgTraje);
        Image fig = new ImageIcon(rutaImgTraje).getImage();

        getJpImgArmadura().getGraphics().drawImage(fig, 0, 0, fig.getWidth(getJpImgArmadura()),fig.getHeight(getJpImgArmadura()),getJpImgArmadura());
    }

    private String obtenerNombreArmadura() {
        switch (numArmadura) {
            case 1:
                return "Mark1";
            case 2:
                return "Mark2";
            case 3:
                return "Mark3";
            case 4:
                return "WarMachine";
            default:
                return "";
        }
    }

    public void putElemento(int numElemento) {
        getJpImgElemento().getGraphics().clearRect(0, 0, 10000, 10000);
        String rutaElemento = carpetaImagenes;
        switch (numElemento) {
            case 1:
                rutaElemento += "Casco";
                break;
            case 2:
                rutaElemento += "Peto";
                break;
            case 3:
                rutaElemento += "Guantes";
                break;
            case 4:
                rutaElemento += "Botas";
                break;
        }
        rutaElemento += obtenerNombreArmadura() + ".jpg";
        // System.out.println(rutaElemento);
        Image fig = new ImageIcon(rutaElemento).getImage();
        // fig = fig.getScaledInstance(100, 100, 1);
        getJpImgElemento().getGraphics().drawImage(fig, 0, 0, fig.getWidth(getJpImgElemento()),
                fig.getHeight(getJpImgElemento()), getJpImgElemento());
    }

    public void agregarLinea(String texto) {
        jtaCaracteristicas.append(texto);
    }

    public JTextArea getJtaCaracteristicas() {
        return jtaCaracteristicas;
    }

    public void setNumArmadura(int numArmadura) {
        this.numArmadura = numArmadura;
        switch (numArmadura) {
            case 1:
                lblNombreTraje.setText("Mark 1");
                break;
            case 2:
                lblNombreTraje.setText("Mark 2");
                break;
            case 3:
                lblNombreTraje.setText("Mark 3");
                break;
            case 4:
                lblNombreTraje.setText("War Machine");
                break;
        }
        putTraje();
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public JPanel getJpImgArmadura() {
        return jpImgArmadura;
    }

    public JPanel getJpImgElemento() {
        return jpImgElemento;
    }

    public JLabel getLblCantidad() {
        return lblCantidad;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpElemento;
    private javax.swing.JPanel jpImgArmadura;
    private javax.swing.JPanel jpImgElemento;
    private javax.swing.JPanel jpTraje;
    private javax.swing.JTextArea jtaCaracteristicas;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblNombreTraje;
    // End of variables declaration//GEN-END:variables
}
